package pojos;
// Generated 28/06/2019 10:25:01 by Hibernate Tools 4.3.1



/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String grade;

    public Students() {
    }

	
    public Students(String firstName) {
        this.firstName = firstName;
    }
    public Students(String firstName, String lastName, String grade) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.grade = grade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }




}


